name: ec2_deploy_listener

on:
  push:
    branches: [ main ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd chat/frontend
            git fetch --all
            git reset --hard origin/main
            git pull origin origin/main
            docker-compose up -d